language: cpp

compiler:
  - gcc
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: windows
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

before_install:
    - eval "${MATRIX_EVAL}"


script:
  - make
